# Makefile with flags
# *******************************
# Paramaters for cross-compiler, warning flags, and gdb flags
# GDB flags should be removed before submission

CC = g++
CFLAGS = -std=c++11 -Wall -g

# *******************************
# Entries for executables

project3: menu.cpp dirGraph.h edge.h graph.h vertex.h
	$(CC) $(CFLAGS) menu.cpp -o proj4
