# Makefile with flags
# *******************************
# Paramaters for cross-compiler, warning flags, and gdb flags

CC = g++
CFLAGS = -std=c++11 -Wall -g

# *******************************
# Entries for executables

project3: menu.cpp avlTree.h linkedTree.h maxHeapTree.h treeNode.h
	$(CC) $(CFLAGS) menu.cpp -o project3
