# Makefile with flags
# *******************************
# Paramaters for cross-compiler, warning flags, and gdb flags

CC = g++
CFLAGS = -std=c++11

# *******************************
# Entries for executables

project2: menu.cpp queue.h stack.h
	$(CC) $(CFLAGS) menu.cpp -o project2
